import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";

import type { CompileTarget } from "./compiler.ts";

const HEADER = "// Generated by znaki. Do not edit.\n";

const TARGET_PRELUDES: Record<CompileTarget, string> = {
  react: `import type { JSX, SVGProps } from "react";
import type { IconName } from "znaki";`,
  solid: `import type { JSX } from "@solidjs/web";
import type { IconName } from "znaki";`,
  reze: `import type { JSX } from "reze-js";
import type { IconName } from "znaki";`,
};

const TARGET_PROPS: Record<CompileTarget, string> = {
  react: `interface IconProps extends Omit<SVGProps<SVGSVGElement>, "name" | "children" | "dangerouslySetInnerHTML"> {`,
  solid: `interface IconProps extends Omit<JSX.SvgSVGAttributes<SVGSVGElement>, "name" | "children" | "innerHTML"> {`,
  reze: `interface IconProps extends Omit<JSX.IntrinsicElements["svg"], "name" | "children" | "innerHTML"> {`,
};

/**
 * Writes the `znaki.d.ts` augmentation: the collected icon names plus the
 * per-target `Icon` / `PreloadSprite` call signatures. The root `znaki`
 * module intentionally declares no component values (they are compile-time
 * intrinsics), so the target-specific signatures can only come from here.
 */
export function writeDts(path: string, names: string[], target: CompileTarget = "react"): void {
  if (!TARGET_PRELUDES[target]) {
    throw new Error(`znaki: unknown target ${JSON.stringify(target)} (expected "react", "solid" or "reze")`);
  }
  const entries = names.map((name) => `    ${JSON.stringify(name)}: never;`).join("\n");
  const content =
    `${HEADER}/* eslint-disable */\n// oxlint-disable\n${TARGET_PRELUDES[target]}\n\n` +
    `declare module "znaki" {\n  interface IconNameMap {\n${entries}\n  }\n\n` +
    `  ${TARGET_PROPS[target]}\n    name: IconName;\n    size?: number | string;\n  }\n\n` +
    `  function Icon(props: IconProps): JSX.Element;\n  function PreloadSprite(): JSX.Element;\n}\n\n` +
    `export {};\n`;

  if (readSafe(path) === content) return;
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content, "utf-8");
}

function readSafe(path: string): string | null {
  try {
    return readFileSync(path, "utf-8");
  } catch {
    return null;
  }
}
