import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";

const HEADER = "// Generated by znaki. Do not edit.\n";

export function writeDts(path: string, names: string[]): void {
  const entries = names.map((name) => `    ${JSON.stringify(name)}: never;`).join("\n");
  const content = `${HEADER}/* eslint-disable */
// oxlint-disable
declare module "znaki" {
  interface IconNameMap {
${entries}
  }
}

export {};
`;

  if (readSafe(path) === content) return;
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content, "utf-8");
}

function readSafe(path: string): string | null {
  try {
    return readFileSync(path, "utf-8");
  } catch {
    return null;
  }
}
