import { readFileSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

import { writeDts } from "../../src/vite/dts.ts";
import { useProject } from "../fixtures/project.ts";

const project = useProject("znaki-dts");

describe("writeDts", () => {
  it("writes a module augmentation for the given names", () => {
    const path = join(project.root, "znaki.d.ts");
    writeDts(path, ["home", "tabler:arrow-right"]);

    expect(readFileSync(path, "utf-8")).toBe(
      `// Generated by znaki. Do not edit.
/* eslint-disable */
// oxlint-disable
declare module "znaki" {
  interface IconNameMap {
    "home": never;
    "tabler:arrow-right": never;
  }
}

export {};
`,
    );
  });

  it("writes an empty interface for no names", () => {
    const path = join(project.root, "znaki.d.ts");
    writeDts(path, []);

    expect(readFileSync(path, "utf-8")).toContain("interface IconNameMap {\n\n  }");
  });

  it("escapes names that need quoting", () => {
    const path = join(project.root, "znaki.d.ts");
    writeDts(path, ['we"ird']);

    expect(readFileSync(path, "utf-8")).toContain(String.raw`"we\"ird": never;`);
  });

  it("creates missing parent directories", () => {
    const path = join(project.root, "a", "b", "znaki.d.ts");
    writeDts(path, ["home"]);

    expect(readFileSync(path, "utf-8")).toContain('"home"');
  });

  it("does not rewrite the file when content is unchanged", async () => {
    const path = join(project.root, "znaki.d.ts");
    writeDts(path, ["home"]);
    const first = statSync(path).mtimeMs;

    await new Promise((r) => setTimeout(r, 10));
    writeDts(path, ["home"]);

    expect(statSync(path).mtimeMs).toBe(first);
  });

  it("rewrites the file when the names change", () => {
    const path = join(project.root, "znaki.d.ts");
    writeDts(path, ["home"]);
    writeDts(path, ["home", "user"]);

    expect(readFileSync(path, "utf-8")).toContain('"user"');
  });

  it("overwrites unrelated existing content", () => {
    const path = join(project.root, "znaki.d.ts");
    writeFileSync(path, "stale");
    writeDts(path, ["home"]);

    expect(readFileSync(path, "utf-8")).not.toContain("stale");
  });
});
